class_name MultimeshIntilize extends Node3D                                                                                                                                                                             
                                                                                                                                                                                                                            
func _ready() -> void:                                                                                                                                                                                                  
        call_deferred("multimeshConverter")                                                                                                                                                                                 
                                                                                                                                                                                                                            
func multimeshConverter():                                                                                                                                                                                              
        var meshGroup = {}                                                                                                                                                                                                  
        # ponytail: just search self, the items are always our children or nested children                                                                                                                                  
        findAndGroupItems(self, meshGroup)                                                                                                                                                                                  
                                                                                                                                                                                                                            
        var total_meshes = meshGroup.size()                                                                                                                                                                                 
        var total_items = 0                                                                                                                                                                                                 
                                                                                                                                                                                                                            
        print("[MultiMesh] Found ", total_meshes, " unique mesh types")                                                                                                                                                     
                                                                                                                                                                                                                            
        for key in meshGroup:                                                                                                                                                                                               
            var items = meshGroup[key]                                                                                                                                                                                      
            total_items += items.size()                                                                                                                                                                                     
            var mesh = items[0]["mesh"]  # get the actual mesh from the first item                                                                                                                                          
            print("[MultiMesh] Mesh '", key, "' -> ", items.size(), " instances")                                                                                                                                           
            buildMultiMesh(mesh, items)                                                                                                                                                                                     
                                                                                                                                                                                                                            
        print("[MultiMesh] Total items converted: ", total_items)                                                                                                                                                           
                                                                                                                                                                                                                            
func findAndGroupItems(currentNode: Node, meshGroup: Dictionary):                                                                                                                                                       
        for child in currentNode.get_children():                                                                                                                                                                            
            if child is Area3D and "realItem" in child:                                                                                                                                                                     
                var visualMeshNode = findFirstMeshIntance(child)                                                                                                                                                            
                                                                                                                                                                                                                            
                if visualMeshNode and visualMeshNode.mesh:                                                                                                                                                                  
                    var mesh = visualMeshNode.mesh                                                                                                                                                                          
                    # Use a string key instead of mesh reference for reliable grouping                                                                                                                                      
                    var key = str(mesh.resource_path) + "|" + str(mesh.resource_name)                                                                                                                                       
                    if key == "|":                                                                                                                                                                                          
                        # sub_resource with no path/name, fall back to RID                                                                                                                                                  
                        key = str(mesh.get_rid())                                                                                                                                                                           
                                                                                                                                                                                                                            
                    if not meshGroup.has(key):                                                                                                                                                                              
                        meshGroup[key] = []                                                                                                                                                                                 
                                                                                                                                                                                                                            
                    meshGroup[key].append({                                                                                                                                                                                 
                        "item": child,                                                                                                                                                                                      
                        "mesh": mesh,  # store the actual mesh for buildMultiMesh                                                                                                                                           
                        "visual_transform": visualMeshNode.global_transform                                                                                                                                                 
                    })                                                                                                                                                                                                      
                    visualMeshNode.visible = false                                                                                                                                                                          
                else:                                                                                                                                                                                                       
                    print("[MultiMesh] WARNING: No mesh found in item: ", child.name)                                                                                                                                       
            findAndGroupItems(child, meshGroup)                                                                                                                                                                             
                                                                                                                                                                                                                            
func buildMultiMesh(mesh: Mesh, items: Array):                                                                                                                                                                          
        var mmi = MultiMeshInstance3D.new()                                                                                                                                                                                 
        var mm = MultiMesh.new()                                                                                                                                                                                            
        mm.transform_format = MultiMesh.TRANSFORM_3D                                                                                                                                                                        
        mm.instance_count = items.size()                                                                                                                                                                                    
        mm.mesh = mesh                                                                                                                                                                                                      
        mmi.multimesh = mm                                                                                                                                                                                                  
        mmi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF                                                                                                                                                     
        mmi.top_level = true                                                                                                                                                                                                
        add_child(mmi)                                                                                                                                                                                                      
        for i in range(items.size()):                                                                                                                                                                                       
            var data = items[i]                                                                                                                                                                                             
            mm.set_instance_transform(i, data["visual_transform"])                                                                                                                                                          
            var fakeItemNode = data["item"]                                                                                                                                                                                 
            fakeItemNode.set_meta("my_multimesh", mmi)                                                                                                                                                                      
            fakeItemNode.set_meta("my_instance_id", i)                                                                                                                                                                      
                                                                                                                                                                                                                            
func findFirstMeshIntance(node: Node) -> MeshInstance3D:                                                                                                                                                                
        if node is MeshInstance3D:                                                                                                                                                                                          
            return node                                                                                                                                                                                                     
        for child in node.get_children():                                                                                                                                                                                   
            var result = findFirstMeshIntance(child)                                                                                                                                                                        
            if result:                                                                                                                                                                                                      
                return result                                                                                                                                                                                               
        return null                                     